services:
  todo-server:
    container_name: todo-server
    image: todo-server:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/Cognixus
    networks:
      - todo-mysql-network
    env_file: .env
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: Cognixus
      MYSQL_USER: jeremygan96
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - todo-mysql-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p$${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
    env_file: .env
networks:
  todo-mysql-network:
    driver: bridge
